const endpoints = {
    pendingReport: '/pending-action/activity-reports',
    pendingParticipant: '/pending-action/plan-participants',
    pendingPlan: '/pending-action/activity-plans',
    narrativeResponse: '/responses',
    activitySchedule: '/activity-schedule',
    activityCount: '/activity-count',
    regionGraph: '/graphs/participants-per-region',
    programmeGraph: '/graphs/participants-per-programme',
    participantAnalysis: '/participant-analysis',
    eventImage: '/event-images',
    profileImage: '/profile-image',
    orgProfile: '/organisation-profile',
    targetGroup: '/target-groups',
    targetRegion: '/target-regions',
    keyProgramme: '/key-programmes',
    donor: '/donors',
    donorContact: '/donor-contacts',
    participant: '/participants',
    proposal: '/proposals',
    objective: '/objectives',
    agenda: '/agenda',
    activity: '/activities',
    activityPlan: '/activity-plans',
    quiz: '/narrative-quiz',
    narrative: '/narrative-reports',
    caseStudy: '/case-studies',
    user: '/users',
    role: '/roles',
    login: '/auth/login',
    logout: '/auth/logout',
    register: '/auth/register',
    resetPassword: '/auth/reset-password',
    recoverPassword: '/auth/recover-password',
    recoveryPassword: '/auth/recovery-password'
};

export default endpoints;